server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://122.51.35.141:3306/webshop?serverTimezone=UTC&characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update